#docker compose -f compose.yaml up -d
version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "/Users/mihailprocenko/PycharmProjects/pythonProject/pytest_lesons/pytest_lesons/homework_pytest_10/selenoid/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/Users/mihailprocenko/PycharmProjects/pythonProject/pytest_lesons/pytest_lesons/homework_pytest_10/selenoid/config/logs:/opt/selenoid/logs"

    command: ["-conf", "/etc/selenoid/browsers.json", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4445:4444"

  selenoid2:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "/Users/mihailprocenko/PycharmProjects/pythonProject/pytest_lesons/pytest_lesons/homework_pytest_10/selenoid/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/Users/mihailprocenko/PycharmProjects/pythonProject/pytest_lesons/pytest_lesons/homework_pytest_10/selenoid/config/logs:/opt/selenoid/logs"

    command: [ "-conf", "/etc/selenoid/browsers.json", "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - "4446:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - ggr-ui
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://192.168.0.106:8888" ]

  ggr:
    restart: always
    image: "aerokube/ggr:latest-release"
    volumes:
      - "/Users/mihailprocenko/PycharmProjects/pythonProject/pytest_lesons/pytest_lesons/homework_pytest_10/selenoid/grid-router:/etc/grid-router:ro"
    ports:
      - "4444:4444"

  ggr-ui:
    network_mode: bridge
    restart: always
    image: "aerokube/ggr-ui:latest-release"
    volumes:
      - "/Users/mihailprocenko/PycharmProjects/pythonProject/pytest_lesons/pytest_lesons/homework_pytest_10/selenoid/grid-router/quota:/etc/grid-router/quota:ro"
    ports:
      - "8888:8888"